language: objective-c
osx_image: xcode10.1
install:
  - bundle install
jobs:
  include:
  - stage: tests
    script: fastlane test
  - stage: release
    deploy:
      provider: script
      script: fastlane beta
      on:
        tags: true
