# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

lane :test do
  run_tests
end
lane :beta do
  # build_app(scheme: "MyNewProject",
  #           workspace: "MyNewWorkspace.xcworkspace")
  # upload to crashlytics
  crashlytics(api_token: ENV['FABRIC_API_TOKEN'],
              build_secret: ENV['FABRIC_API_SECRET']) if ENV['FABRIC_API_TOKEN'] && ENV['FABRIC_API_SECRET']
  # Upload to apple testflight
  
  upload_to_testflight
  # Upload to hockey app
  
  # hockey(api_token: ENV['HOCKEY_API_TOKEN'])

end
